SET search_path TO PUBLIC;


CREATE SCHEMA IF NOT EXISTS tag;


CREATE TYPE tag.pos_class AS ENUM(
	'penn_treebank',
	'universal'
);


CREATE TABLE IF NOT EXISTS tag.pos(
	_id	BIGSERIAL PRIMARY KEY,
	_class	tag.pos_class NOT NULL,
	_pos	VARCHAR(5) NOT NULL UNIQUE,
	_def	VARCHAR(128) NOT NULL
);


CREATE TABLE IF NOT EXISTS tag.dependency(
	_id	BIGSERIAL PRIMARY KEY,
	_label	VARCHAR(16) NOT NULL UNIQUE,
	_def	VARCHAR(128) NOT NULL
);


CREATE TABLE IF NOT EXISTS tag.entity(
	_id	BIGSERIAL PRIMARY KEY,
	_name	VARCHAR(16) NOT NULL UNIQUE,
	_def	VARCHAR(128) NOT NULL
);


GRANT USAGE ON SCHEMA tag TO nlpx;
GRANT SELECT ON ALL TABLES IN SCHEMA tag TO nlpx;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA tag TO nlpx;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA tag TO nlpx;

