SET SEARCH_PATH TO PUBLIC;

BEGIN;
	DROP TABLE IF EXISTS _corpus CASCADE;
	DROP TABLE IF EXISTS _upenn_treebank_tagset CASCADE;
	DROP TABLE IF EXISTS _lexicon CASCADE;

	DROP PROCEDURE lexicon_add;
END;

