set search_path to public;


CREATE TABLE IF NOT EXISTS _title(
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(256) NOT NULL,
	author VARCHAR(512) NOT NULL);


CREATE TABLE IF NOT EXISTS _pos(
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(5) NOT NULL UNIQUE,
	desc VARCHAR(128) NOT NULL);


CREATE TABLE IF NOT EXISTS _token(
	id BIGSERIAL PRIMARY KEY,
	pos BIGINT REFERENCES _pos(id) ON DELETE CASCADE,
	flag INT,
	value VARCHAR(64) NOT NULL);


CREATE TABLE IF NOT EXISTS _title_token(
	id BIGSERIAL PRIMARY KEY,
	title BIGINT REFERENCES _title(id) ON DELETE CASCADE,
	token BIGINT REFERENCES _token(id) ON DELETE CASCADE,
	paragraph BIGINT NOT NULL,
	sentence BIGINT NOT NULL,
	position BIGINT NOT NULL);

